import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const generateStatementPDF = (record: any, events: any[]) => {
  const doc = new jsPDF();
  
  // -- Branding / Header --
  doc.setFillColor(37, 99, 235); // Blue-600 header bg
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("Storage Statement", 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(`Generated: ${format(new Date(), 'PPP')}`, 14, 28);

  doc.setFontSize(16);
  doc.text("Grain Flow", 196, 20, { align: 'right' });
  
  // -- Record Identity --
  doc.setTextColor(15, 23, 42); // Slate-900
  doc.setFontSize(14);
  doc.text(`${record.crops?.name || 'Crop Name'}`, 14, 55);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.text(`Lot: ${record.lot_name || 'N/A'}`, 14, 61);
  doc.text(`Record #${record.record_number || record.id?.slice(0, 8)}`, 50, 61); // Beside Lot
  
  // -- KPI Cards (Visual approximation) --
  // Card 1: Current Stock
  doc.setDrawColor(226, 232, 240); // Slate-200
  doc.setFillColor(248, 250, 252); // Slate-50
  doc.roundedRect(14, 70, 85, 25, 3, 3, 'FD');
  
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("CURRENT STOCK", 20, 78);
  
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(`${record.bags_stored} Bags`, 20, 88);

  // Card 2: Balance Due
  doc.roundedRect(109, 70, 85, 25, 3, 3, 'FD');
  
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("BALANCE DUE", 115, 78);
  
  doc.setFontSize(16);
  const due = record.billed - record.paid;
  if (due > 0) {
      doc.setTextColor(220, 38, 38); // Red-600
  } else {
      doc.setTextColor(22, 163, 74); // Green-600
  }
  doc.text(`Rs. ${due}`, 115, 88);

  // -- Transaction History Table --
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Transaction History", 14, 110);

  const tableBody = events.map(e => {
    let typeDisplay = e.title;
    let amountDisplay = '';
    
    if (e.type === 'DEPOSIT') {
        amountDisplay = `+${e.amount} Bags`;
    } else if (e.type === 'WITHDRAWAL') {
        typeDisplay = 'Stock Withdrawal'; // Explicit label
        amountDisplay = `-${e.amount} Bags`;
    } else if (e.type === 'PAYMENT') {
        amountDisplay = `Rs. ${e.amount}`;
    }

    return [
        format(new Date(e.date), 'MMM d, yyyy'),
        typeDisplay,
        amountDisplay
    ];
  });

  autoTable(doc, {
    startY: 115,
    head: [['Date', 'Activity', 'Amount']],
    body: tableBody,
    theme: 'grid',
    styles: { 
        fontSize: 10,
        cellPadding: 4
    },
    headStyles: { 
        fillColor: [241, 245, 249], // Slate-100 header
        textColor: [51, 65, 85], // Slate-700 text
        fontStyle: 'bold',
        lineWidth: 0
    },
    columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 40, halign: 'right', fontStyle: 'bold' }
    },
    didParseCell: function(data) {
        if (data.section === 'body' && data.column.index === 2) {
            const text = data.cell.raw as string;
            if (text.includes('+')) data.cell.styles.textColor = [22, 163, 74]; // Green
            if (text.includes('-')) data.cell.styles.textColor = [220, 38, 38]; // Red
            if (text.includes('Rs.')) data.cell.styles.textColor = [37, 99, 235]; // Blue
        }
    }
  });

  // Footer
  const finalY = (doc as any).lastAutoTable.finalY + 20;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Grain Flow Customer Portal", 14, finalY);

  // Save
  doc.save(`Statement_${record.record_number || 'Record'}.pdf`);
};

export const generateConsolidatedPDF = (portfolio: any[]) => {
    const doc = new jsPDF();
    
    // -- Header --
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("Stock & Account Statement", 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${format(new Date(), 'PPP')}`, 14, 26);
    
    let grandTotalCurrent = 0;
    let grandTotalWithdrawn = 0;
    let grandTotalInitial = 0;
    let grandTotalDue = 0;

    // -- Flatten Records --
    const allRecords = portfolio.flatMap(wh => {
        return wh.records.filter((r: any) => r.is_active).map((r: any) => {
            const withdrawals = r.withdrawal_transactions || [];
            const totalWithdrawn = withdrawals.reduce((sum: number, w: any) => sum + (w.bags_withdrawn || 0), 0);
            const currentStock = r.bags_stored || 0;
            const initialStock = currentStock + totalWithdrawn;
            const balanceDue = r.billed - r.paid;

            grandTotalCurrent += currentStock;
            grandTotalWithdrawn += totalWithdrawn;
            grandTotalInitial += initialStock;
            grandTotalDue += balanceDue;

            return {
                warehouse: wh.warehouseName,
                crop: r.crops?.name || 'Crop',
                lot: r.lot_name || 'N/A',
                recordNo: r.record_number || r.id.slice(0, 8),
                date: r.storage_start_date,
                initial: initialStock,
                withdrawn: totalWithdrawn,
                current: currentStock,
                billed: r.billed,
                paid: r.paid,
                due: balanceDue
            };
        });
    });

    // -- Summary Box --
    doc.setDrawColor(220, 220, 220);
    doc.setFillColor(248, 250, 252); // Slate-50
    doc.roundedRect(14, 35, 182, 30, 3, 3, 'FD');
    
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42); // Slate-900
    doc.text("Portfolio Snapshot", 20, 46);
    
    // Summary Grid
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139); // Slate-500
    doc.text("TOTAL DEPOSITED", 20, 54);
    doc.text("TOTAL WITHDRAWN", 65, 54);
    doc.text("CURRENT STOCK", 110, 54);
    
    // Dynamic Header for Finance
    if (grandTotalDue > 0) {
        doc.text("OUTSTANDING DUES", 155, 54);
        doc.setTextColor(220, 38, 38); // Red-600
        doc.setFontSize(12);
        doc.text(`Rs. ${grandTotalDue}`, 155, 60);
    } else if (grandTotalDue < 0) {
        doc.text("TOTAL ADVANCE / CREDIT", 155, 54);
        doc.setTextColor(22, 163, 74); // Green-600
        doc.setFontSize(12);
        doc.text(`Rs. ${Math.abs(grandTotalDue)}`, 155, 60);
    } else {
        doc.text("ACCOUNT STATUS", 155, 54);
        doc.setTextColor(22, 163, 74); // Green-600
        doc.setFontSize(12);
        doc.text(`Settled`, 155, 60);
    }

    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42); // Slate-900 (Restore color for other columns)
    doc.text(`${grandTotalInitial} Bags`, 20, 60);
    doc.text(`${grandTotalWithdrawn} Bags`, 65, 60);
    doc.text(`${grandTotalCurrent} Bags`, 110, 60);

    // -- Detailed Table --
    const tableBody = allRecords.map(r => {
        let balanceDisplay = 'Paid';
        if (r.due > 0) balanceDisplay = `Rs. ${r.due}`;
        if (r.due < 0) balanceDisplay = `Cr. Rs. ${Math.abs(r.due)}`;
        
        return [
            format(new Date(r.date), 'dd/MM/yy'),
            `${r.crop}\nLot: ${r.lot} (#${r.recordNo})`,
            r.initial,
            r.withdrawn > 0 ? `-${r.withdrawn}` : '-',
            r.current,
            balanceDisplay
        ];
    });

    autoTable(doc, {
        startY: 80,
        head: [['Date', 'Item Details', 'In', 'Out', 'Stock', 'Balance']],
        body: tableBody,
        theme: 'grid',
        styles: { 
            fontSize: 9, 
            cellPadding: 3,
            valign: 'middle'
        },
        headStyles: { 
            fillColor: [30, 41, 59], // Slate-800
            textColor: 255,
            fontStyle: 'bold'
        },
        columnStyles: {
            0: { cellWidth: 25 },
            1: { cellWidth: 'auto' }, // Item Details
            2: { cellWidth: 20, halign: 'center' }, // In
            3: { cellWidth: 20, halign: 'center' }, // Out
            4: { cellWidth: 20, halign: 'center', fontStyle: 'bold' }, // Stock
            5: { cellWidth: 30, halign: 'right', fontStyle: 'bold' } // Balance styling handled in hook
        },
        didParseCell: function(data) {
            // Color coding for Balance column
            if (data.column.index === 5 && data.section === 'body') {
                const text = data.cell.raw as string;
                if (text === 'Paid') {
                    data.cell.styles.textColor = [22, 163, 74]; // Green-600
                } else if (text.startsWith('Cr.')) {
                    data.cell.styles.textColor = [37, 99, 235]; // Blue-600 (Credit)
                } else {
                    data.cell.styles.textColor = [220, 38, 38]; // Red-600 (Due)
                }
            }
        }
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Note: 'In' = Initial Deposit, 'Out' = Total Withdrawals, 'Stock' = Currently in Warehouse.", 14, finalY);

    // Save
    doc.save(`GrainFlow_Report_${format(new Date(), 'dd-MM-yyyy')}.pdf`);
};
