-- schema_public_full.sql
-- Full DDL export for public schema (structure only, no data).
-- Generated from your project's current public schema.
-- Review and run in a safe environment. Adjust extensions if needed.

-- 1) Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- gen_random_uuid() and gen_random_bytes() are provided by pgcrypto in many setups.
-- If your environment uses uuid-ossp, change defaults accordingly.

-- 2) Types
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_roles') THEN
    CREATE TYPE public.user_roles AS ENUM ('admin','manager','staff','super_admin','owner','customer');
  END IF;
END$$;

-- 3) Tables

-- Table: warehouses
CREATE TABLE IF NOT EXISTS public.warehouses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text,
  capacity_bags integer,
  created_at timestamptz DEFAULT now(),
  phone text,
  email text,
  PRIMARY KEY (id)
);

-- Table: customers
CREATE TABLE IF NOT EXISTS public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  address text NOT NULL,
  father_name text,
  village text,
  created_at timestamptz DEFAULT now(),
  warehouse_id uuid,
  linked_user_id uuid,
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: crops
CREATE TABLE IF NOT EXISTS public.crops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  warehouse_id uuid,
  name text NOT NULL,
  rent_price_6m numeric,
  rent_price_1y numeric,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: warehouse_lots
CREATE TABLE IF NOT EXISTS public.warehouse_lots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  warehouse_id uuid NOT NULL,
  name text NOT NULL,
  status text DEFAULT 'Active',
  created_at timestamptz DEFAULT now(),
  capacity integer DEFAULT 1000,
  current_stock integer DEFAULT 0 CHECK (current_stock >= 0),
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL,
  warehouse_id uuid,
  full_name text,
  email text,
  role public.user_roles DEFAULT 'staff',
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: storage_records
CREATE TABLE IF NOT EXISTS public.storage_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  commodity_description text,
  location text,
  bags_stored integer CHECK (bags_stored >= 0),
  lorry_tractor_no text,
  inflow_type text,
  plot_bags integer,
  load_bags integer,
  khata_amount numeric,
  storage_start_date timestamptz,
  storage_end_date timestamptz,
  billing_cycle text,
  hamali_payable numeric,
  total_rent_billed numeric,
  created_at timestamptz DEFAULT now(),
  warehouse_id uuid,
  crop_id uuid,
  lot_id uuid,
  record_number bigint GENERATED BY DEFAULT AS IDENTITY,
  outflow_invoice_no text,
  bags_in integer DEFAULT 0 CHECK (bags_in >= 0),
  bags_out integer DEFAULT 0,
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: payments
CREATE TABLE IF NOT EXISTS public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  storage_record_id uuid,
  amount numeric NOT NULL CHECK (amount > 0),
  payment_date timestamptz DEFAULT now(),
  notes text,
  created_at timestamptz DEFAULT now(),
  payment_number bigint GENERATED BY DEFAULT AS IDENTITY,
  type text CHECK (type = ANY (ARRAY['rent','hamali','other'])),
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: expenses
CREATE TABLE IF NOT EXISTS public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  description text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0),
  category text,
  expense_date timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  warehouse_id uuid,
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: activity_logs
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  warehouse_id uuid,
  user_id uuid,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id uuid,
  details jsonb,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  warehouse_id uuid,
  user_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text DEFAULT 'info',
  is_read boolean DEFAULT false,
  link text,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: notification_reads
CREATE TABLE IF NOT EXISTS public.notification_reads (
  notification_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamptz DEFAULT now(),
  PRIMARY KEY (notification_id, user_id)
);

-- Table: sequences
CREATE TABLE IF NOT EXISTS public.sequences (
  warehouse_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['inflow','outflow'])),
  current_value integer DEFAULT 0,
  last_reset timestamptz DEFAULT now(),
  PRIMARY KEY (warehouse_id, type)
);

-- Table: warehouse_assignments
CREATE TABLE IF NOT EXISTS public.warehouse_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  warehouse_id uuid,
  role text DEFAULT 'staff' CHECK (role = ANY (ARRAY['owner','admin','manager','staff','super_admin'])),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: warehouse_invitations
CREATE TABLE IF NOT EXISTS public.warehouse_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  warehouse_id uuid,
  role text DEFAULT 'staff',
  token text NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(16), 'hex'),
  created_by uuid,
  status text DEFAULT 'pending' CHECK (status = ANY (ARRAY['pending','accepted','expired'])),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  claimed_by uuid,
  PRIMARY KEY (id)
);

-- Table: withdrawal_transactions
CREATE TABLE IF NOT EXISTS public.withdrawal_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  warehouse_id uuid NOT NULL,
  storage_record_id uuid NOT NULL,
  bags_withdrawn integer NOT NULL,
  withdrawal_date date NOT NULL,
  rent_collected numeric DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: user_warehouses
CREATE TABLE IF NOT EXISTS public.user_warehouses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  warehouse_id uuid NOT NULL,
  role text DEFAULT 'staff',
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);

-- 4) Foreign key constraints
ALTER TABLE public.customers
  ADD CONSTRAINT customers_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL,
  ADD CONSTRAINT customers_linked_user_id_fkey FOREIGN KEY (linked_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.crops
  ADD CONSTRAINT crops_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;

ALTER TABLE public.warehouse_lots
  ADD CONSTRAINT warehouse_lots_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE CASCADE;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL,
  ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.storage_records
  ADD CONSTRAINT storage_records_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL,
  ADD CONSTRAINT storage_records_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES public.warehouse_lots(id) ON DELETE SET NULL,
  ADD CONSTRAINT storage_records_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL,
  ADD CONSTRAINT storage_records_crop_id_fkey FOREIGN KEY (crop_id) REFERENCES public.crops(id) ON DELETE SET NULL;

ALTER TABLE public.payments
  ADD CONSTRAINT payments_storage_record_id_fkey FOREIGN KEY (storage_record_id) REFERENCES public.storage_records(id) ON DELETE SET NULL;

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;

ALTER TABLE public.activity_logs
  ADD CONSTRAINT activity_logs_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL,
  ADD CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.notifications
  ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD CONSTRAINT notifications_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;

ALTER TABLE public.notification_reads
  ADD CONSTRAINT notification_reads_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id) ON DELETE CASCADE,
  ADD CONSTRAINT notification_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.sequences
  ADD CONSTRAINT sequences_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE CASCADE;

ALTER TABLE public.warehouse_assignments
  ADD CONSTRAINT warehouse_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD CONSTRAINT warehouse_assignments_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE CASCADE;

ALTER TABLE public.warehouse_invitations
  ADD CONSTRAINT warehouse_invitations_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL,
  ADD CONSTRAINT warehouse_invitations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD CONSTRAINT warehouse_invitations_claimed_by_fkey FOREIGN KEY (claimed_by) REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.withdrawal_transactions
  ADD CONSTRAINT withdrawal_transactions_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE CASCADE,
  ADD CONSTRAINT withdrawal_transactions_storage_record_id_fkey FOREIGN KEY (storage_record_id) REFERENCES public.storage_records(id) ON DELETE CASCADE;

ALTER TABLE public.user_warehouses
  ADD CONSTRAINT user_warehouses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD CONSTRAINT user_warehouses_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE CASCADE;

-- 5) Indexes (suggested)
-- Primary keys create unique indexes automatically.
-- Uncomment or adjust the indexes below according to your workload.

-- CREATE INDEX IF NOT EXISTS idx_storage_records_customer_id ON public.storage_records(customer_id);
-- CREATE INDEX IF NOT EXISTS idx_storage_records_warehouse_id ON public.storage_records(warehouse_id);
-- CREATE INDEX IF NOT EXISTS idx_storage_records_lot_id ON public.storage_records(lot_id);
-- CREATE INDEX IF NOT EXISTS idx_storage_records_crop_id ON public.storage_records(crop_id);
-- CREATE INDEX IF NOT EXISTS idx_payments_storage_record_id ON public.payments(storage_record_id);
-- CREATE INDEX IF NOT EXISTS idx_notification_reads_user_id ON public.notification_reads(user_id);
-- CREATE INDEX IF NOT EXISTS idx_profiles_warehouse_id ON public.profiles(warehouse_id);
-- CREATE INDEX IF NOT EXISTS idx_warehouse_lots_warehouse_id ON public.warehouse_lots(warehouse_id);
-- CREATE INDEX IF NOT EXISTS idx_user_warehouses_user_id ON public.user_warehouses(user_id);
-- CREATE INDEX IF NOT EXISTS idx_user_warehouses_warehouse_id ON public.user_warehouses(warehouse_id);

-- 6) Trigger helper for updated_at (optional)
-- Uncomment to create a reusable function and example triggers that set updated_at = now() on UPDATE.

-- CREATE OR REPLACE FUNCTION public.set_updated_at()
-- RETURNS TRIGGER LANGUAGE plpgsql AS $$
-- BEGIN
--   NEW.updated_at = now();
--   RETURN NEW;
-- END;
-- $$;

-- Example triggers (uncomment one per table you want to auto-update updated_at):
-- CREATE TRIGGER trg_set_updated_at_storage_records
-- BEFORE UPDATE ON public.storage_records
-- FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- CREATE TRIGGER trg_set_updated_at_payments
-- BEFORE UPDATE ON public.payments
-- FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- CREATE TRIGGER trg_set_updated_at_crops
-- BEFORE UPDATE ON public.crops
-- FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- CREATE TRIGGER trg_set_updated_at_warehouse_lots
-- BEFORE UPDATE ON public.warehouse_lots
-- FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- CREATE TRIGGER trg_set_updated_at_warehouse_assignments
-- BEFORE UPDATE ON public.warehouse_assignments
-- FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- CREATE TRIGGER trg_set_updated_at_withdrawal_transactions
-- BEFORE UPDATE ON public.withdrawal_transactions
-- FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 7) RLS notes
-- Your exported schema had RLS enabled on many tables. This file does NOT create any RLS policies.
-- If you need RLS policies (e.g., restrict access to warehouse members), tell me and I will append recommended policies.

-- End of schema_public_full.sql